// Exercise image mapping - from free-exercise-db (public domain)
// Each exercise has 2 images: start position [0] and end position [1]
const EXERCISE_IMAGES = {
  "Alternating Lunges": ["img/Alternating_Lunges_0.jpg", "img/Alternating_Lunges_1.jpg"],
  "Arm Circles": ["img/Arm_Circles_0.jpg", "img/Arm_Circles_1.jpg"],
  "Bicycle Crunches": ["img/Bicycle_Crunches_0.jpg", "img/Bicycle_Crunches_1.jpg"],
  "Bird Dogs": ["img/Bird_Dogs_0.jpg", "img/Bird_Dogs_1.jpg"],
  "Calf Raises": ["img/Calf_Raises_0.jpg", "img/Calf_Raises_1.jpg"],
  "Crunches": ["img/Crunches_0.jpg", "img/Crunches_1.jpg"],
  "Curtsy Lunges": ["img/Curtsy_Lunges_0.jpg", "img/Curtsy_Lunges_1.jpg"],
  "Dead Bug": ["img/Dead_Bug_0.jpg", "img/Dead_Bug_1.jpg"],
  "Decline Push-Ups": ["img/Decline_Push_Ups_0.jpg", "img/Decline_Push_Ups_1.jpg"],
  "Diamond Push-Ups": ["img/Diamond_Push_Ups_0.jpg", "img/Diamond_Push_Ups_1.jpg"],
  "Donkey Kicks": ["img/Donkey_Kicks_0.jpg", "img/Donkey_Kicks_1.jpg"],
  "Flutter Kicks": ["img/Flutter_Kicks_0.jpg", "img/Flutter_Kicks_1.jpg"],
  "Glute Bridges": ["img/Glute_Bridges_0.jpg", "img/Glute_Bridges_1.jpg"],
  "High Knees": ["img/High_Knees_0.jpg", "img/High_Knees_1.jpg"],
  "Inchworms": ["img/Inchworms_0.jpg", "img/Inchworms_1.jpg"],
  "Jump Squats": ["img/Jump_Squats_0.jpg", "img/Jump_Squats_1.jpg"],
  "Jumping Jacks": ["img/Jumping_Jacks_0.jpg", "img/Jumping_Jacks_1.jpg"],
  "Lateral Lunges": ["img/Lateral_Lunges_0.jpg", "img/Lateral_Lunges_1.jpg"],
  "Leg Raises": ["img/Leg_Raises_0.jpg", "img/Leg_Raises_1.jpg"],
  "Lunges": ["img/Lunges_0.jpg", "img/Lunges_1.jpg"],
  "Mountain Climbers": ["img/Mountain_Climbers_0.jpg", "img/Mountain_Climbers_1.jpg"],
  "Pike Push-Ups": ["img/Pike_Push_Ups_0.jpg", "img/Pike_Push_Ups_1.jpg"],
  "Plank": ["img/Plank_0.jpg", "img/Plank_1.jpg"],
  "Plank Shoulder Taps": ["img/Plank_Shoulder_Taps_0.jpg", "img/Plank_Shoulder_Taps_1.jpg"],
  "Plank Up-Downs": ["img/Plank_Up_Downs_0.jpg", "img/Plank_Up_Downs_1.jpg"],
  "Push-Up & Rotate": ["img/Push_Up_and_Rotate_0.jpg", "img/Push_Up_and_Rotate_1.jpg"],
  "Push-Ups": ["img/Push_Ups_0.jpg", "img/Push_Ups_1.jpg"],
  "Russian Twists": ["img/Russian_Twists_0.jpg", "img/Russian_Twists_1.jpg"],
  "Shoulder Taps": ["img/Shoulder_Taps_0.jpg", "img/Shoulder_Taps_1.jpg"],
  "Side Plank": ["img/Side_Plank_0.jpg", "img/Side_Plank_1.jpg"],
  "Side Plank Left": ["img/Side_Plank_Left_0.jpg", "img/Side_Plank_Left_1.jpg"],
  "Side Plank Right": ["img/Side_Plank_Right_0.jpg", "img/Side_Plank_Right_1.jpg"],
  "Single-Leg Deadlift": ["img/Single_Leg_Deadlift_0.jpg", "img/Single_Leg_Deadlift_1.jpg"],
  "Squat Hold": ["img/Squat_Hold_0.jpg", "img/Squat_Hold_1.jpg"],
  "Squats": ["img/Squats_0.jpg", "img/Squats_1.jpg"],
  "Step-Up onto Chair": ["img/Step_Up_onto_Chair_0.jpg", "img/Step_Up_onto_Chair_1.jpg"],
  "Sumo Squats": ["img/Sumo_Squats_0.jpg", "img/Sumo_Squats_1.jpg"],
  "Superman Hold": ["img/Superman_Hold_0.jpg", "img/Superman_Hold_1.jpg"],
  "Superman Pulls": ["img/Superman_Pulls_0.jpg", "img/Superman_Pulls_1.jpg"],
  "Tricep Dips": ["img/Tricep_Dips_0.jpg", "img/Tricep_Dips_1.jpg"],
  "V-Ups": ["img/V_Ups_0.jpg", "img/V_Ups_1.jpg"],
  "Wall Sit": ["img/Wall_Sit_0.jpg", "img/Wall_Sit_1.jpg"],
  "Wide Push-Ups": ["img/Wide_Push_Ups_0.jpg", "img/Wide_Push_Ups_1.jpg"],
};